Add missing template type specification - fix #181
cg-tuwien/Auto-Vk-Toolkit pull request #183
Opened 2023-10-16 22:34 UTC by MatejSakmary

As described in the linked issue this fixes the compilation problem for all but `skinned_meshlets` projects. I don't how to and if I should even add command line option into the project settings so that it shows up in git. So that error is still unresolved by this PR.

2023-10-21 09:48 UTC, johannesugb commented
> Edit: Uh Github apparently allows creating multiple PRs only by creating multiple branches, 

This is fine for now. I'll add you as contributor to the two repositories, then it is less cumbersome to create multiple branches. For fixing #181 and #182, let's just keep it like this in a common PR.

> I have no idea how submodules work with PR changes so to be sure I've split this into a PR for this repo and PR for Auto-Vk, hope it's okay...

I don't think that there's a super-clean way of handling submodules, at least not that I know of. I.e., two PRs, one for each repository, is the way to go.

2023-10-21 09:49 UTC, johannesugb requested changes
Great work so far! 💪 

Just one validation error remains:
```
Validation Error: [ VUID-VkMemoryBarrier2-dstAccessMask-07454 ] Object 0: handle = 0x2499b8be070, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0xade1a5bb | vkCmdPipelineBarrier2(): pDependencyInfo.pMemoryBarriers[0].dstAccessMask bit VK_ACCESS_SHADER_READ_BIT is not supported by stage mask (VK_PIPELINE_STAGE_ACCELERATION_STRUCTURE_BUILD_BIT_KHR). The Vulkan spec states: If pname:dstAccessMask includes VK_ACCESS_2_SHADER_READ_BIT, pname:dstStageMask must include VK_PIPELINE_STAGE_2_ALL_GRAPHICS_BIT, VK_PIPELINE_STAGE_2_ALL_COMMANDS_BIT, VK_PIPELINE_STAGE_2_ACCELERATION_STRUCTURE_BUILD_BIT_KHR, VK_PIPELINE_STAGE_2_MICROMAP_BUILD_BIT_EXT, or one of the VK_PIPELINE_STAGE_*_SHADER_BIT stages (https://vulkan.lunarg.com/doc/view/1.3.261.1/windows/1.3-extensions/vkspec.html#VUID-VkMemoryBarrier2-dstAccessMask-07454)
```

Interestingly, this only occurs in the `ray_query_in_ray_tracing_shaders` example, but not in the `ray_tracing_custom_intersection` or `ray_tracing_with_shadows_and_ao` examples. Could you have one more look into this?

2023-10-21 10:11 UTC, MatejSakmary commented
I can try to take a look, but unfortunately I cannot test if I have truly fixed the issue :( This is because I only have GeForce GTX 1080 which does not support rt queries, so the example fails to run for me as the extension is detected missing.

Nonetheless I can still attempt a fix and check with you if it runs without any issues, if you are okay with that.

2023-10-21 10:21 UTC, johannesugb commented
> I can try to take a look, but unfortunately I cannot test if I have truly fixed the issue :( This is because I only have GeForce GTX 1080 which does not support rt queries, so the example fails to run for me as the extension is detected missing.
> 
> Nonetheless I can still attempt a fix and check with you if it runs without any issues, if you are okay with that.

Ah, yeah. I see. Then do not spend too much time on it. I can take a look at some point in the future. But thanks! :)

And while you're at it, may I ask you to also have a quick look at issue #184 ? 🙏 
If it is fixable quickly, we could add that to this PR as well.

2023-10-22 14:00 UTC, MatejSakmary commented
I pushed a fix which should remove the last validation errors in `ray_query_in_ray_tracing_shaders`.

As for #184 I can't replicate the issue. I tried both Development and timeline-semaphores branch of Auto-vk and I am using the Development branch for Auto-vk-toolkit. Are there more steps to replicate the issue?

2023-10-23 08:21 UTC, johannesugb approved these changes
Great work, thanks!

2023-10-23 08:22 UTC, johannesugb commented
> I pushed a fix which should remove the last validation errors in `ray_query_in_ray_tracing_shaders`.

Well done! ...especially without the ability to test the ray tracing examples. 💪 

> As for #184 I can't replicate the issue. I tried both Development and timeline-semaphores branch of Auto-vk and I am using the Development branch for Auto-vk-toolkit. Are there more steps to replicate the issue?

Okay, all of a sudden the issue does not appear on my machine as well. 🤔           
I guess this is resolved. ^^

2023-10-23 08:23 UTC, merged